#!/usr/bin/env bash
#
# moonlight-pi-setup.sh
#
# Turns a Raspberry Pi 5 running Raspberry Pi OS (64-bit, Trixie; Lite or desktop)
# into a Moonlight game-streaming client that can boot straight into Moonlight.
#
# Usage:
#   ./moonlight-pi-setup.sh              Install, or re-run to change settings
#   ./moonlight-pi-setup.sh --uninstall  Undo the changes this script made
#   ./moonlight-pi-setup.sh --force      Skip the hardware/OS checks (unsupported)
#   ./moonlight-pi-setup.sh --help       Show help
#
set -Eeuo pipefail

SCRIPT_VERSION="1.4.0"

# Change this to your own repository before publishing.
REPO_URL="https://github.com/joshmichael/moonlight-pi-setup"
ISSUES_URL="${REPO_URL}/issues"
RAW_SCRIPT_URL="https://raw.githubusercontent.com/joshmichael/moonlight-pi-setup/main/moonlight-pi-setup.sh"

# ---------------------------------------------------------------------------
# Paths and constants
# ---------------------------------------------------------------------------
USER_NAME="$(id -un)"
STATE_DIR="${HOME}/.local/share/moonlight-pi-setup"
BACKUP_DIR="${STATE_DIR}/backups"
STATE_FILE="${STATE_DIR}/state"
SAVED_SCRIPT="${STATE_DIR}/moonlight-pi-setup.sh"
CONFIG_DIR="${HOME}/.config/moonlight-pi-setup"
EGLFS_CONFIG="${CONFIG_DIR}/eglfs.json"
ASOUNDRC="${HOME}/.asoundrc"
BASH_PROFILE="${HOME}/.bash_profile"
SYSCTL_FILE="/etc/sysctl.d/90-moonlight-pi-setup.conf"
CMDLINE_FILE="/boot/firmware/cmdline.txt"
CONFIG_TXT="/boot/firmware/config.txt"
AUTOLOGIN_DROPIN="/etc/systemd/system/getty@tty1.service.d/autologin.conf"
LIGHTDM_CONF="/etc/lightdm/lightdm.conf"
NM_WIFI_CONF="/etc/NetworkManager/conf.d/90-moonlight-pi-setup-wifi.conf"

MOONLIGHT_REPO_SCRIPT="https://dl.cloudsmith.io/public/moonlight-game-streaming/moonlight-qt/setup.deb.sh"
TAILSCALE_INSTALL_SCRIPT="https://tailscale.com/install.sh"
VH_INSTALL_SCRIPT="https://raw.githubusercontent.com/virtualhere/script/main/install_server"
VH_UNINSTALL_SCRIPT="https://raw.githubusercontent.com/virtualhere/script/main/uninstall_server"
QUIT_HELPER="/usr/local/bin/moonlight-quit-all"
QUIT_SERVICE_NAME="moonlight-quit-on-shutdown.service"
QUIT_SERVICE="/etc/systemd/system/${QUIT_SERVICE_NAME}"

MARK_BEGIN="# >>> moonlight-pi-setup >>>"
MARK_END="# <<< moonlight-pi-setup <<<"
ASOUND_HEADER="# Generated by moonlight-pi-setup"
QUIET_TOKENS=(quiet loglevel=3 logo.nologo vt.global_cursor_default=0)

# Settings chosen during the run
FORCE=0
OS_CODENAME=""
HDMI_PORT=""
DISPLAY_DEVICE=""
AUDIO_MODE=""          # stereo | 5.1 | 7.1 | system
OPT_AUTOSTART=0
IS_DESKTOP=0
HAS_AUDIO_SERVER=0
OPT_QUIET_BOOT=0
OPT_QUIT_ON_SHUTDOWN=0
OPT_TAILSCALE=0
OPT_VIRTUALHERE=0
OPT_WIFI_POWERSAVE_OFF=0
NET_IFACE=""
ON_WIFI=0
SUDO_KEEPALIVE_PID=""

# ---------------------------------------------------------------------------
# Output helpers
# ---------------------------------------------------------------------------
if [[ -t 1 ]]; then
  C_BOLD=$'\e[1m'; C_RED=$'\e[31m'; C_GREEN=$'\e[32m'; C_YELLOW=$'\e[33m'
  C_BLUE=$'\e[34m'; C_RESET=$'\e[0m'
else
  C_BOLD=""; C_RED=""; C_GREEN=""; C_YELLOW=""; C_BLUE=""; C_RESET=""
fi

step()  { printf '\n%s==> %s%s\n' "${C_BOLD}${C_BLUE}" "$*" "${C_RESET}"; }
info()  { printf '    %s\n' "$*"; }
ok()    { printf '    %s[OK]%s %s\n' "${C_GREEN}" "${C_RESET}" "$*"; }
warn()  { printf '    %s[WARNING]%s %s\n' "${C_YELLOW}" "${C_RESET}" "$*"; }
error() { printf '    %s[ERROR]%s %s\n' "${C_RED}" "${C_RESET}" "$*" >&2; }
die()   { error "$*"; exit 1; }

on_error() {
  local line=$1
  error "Something went wrong (line ${line})."
  if [[ -n "${LOG_FILE:-}" ]]; then
    error "A full log of this run is saved at: ${LOG_FILE}"
  fi
  error "If you think this is a bug, please report it at: ${ISSUES_URL}"
}
trap 'on_error $LINENO' ERR

cleanup() {
  if [[ -n "${SUDO_KEEPALIVE_PID}" ]]; then
    kill "${SUDO_KEEPALIVE_PID}" 2>/dev/null || true
  fi
}
trap cleanup EXIT

# Read a line from the terminal, even when the script is piped into bash.
read_tty() {
  local __var=$1 __reply=""
  if ! read -r __reply < /dev/tty; then
    __reply=""
  fi
  printf -v "$__var" '%s' "$__reply"
}

# ask_yes_no "Question" y|n   -> returns 0 for yes, 1 for no
ask_yes_no() {
  local prompt=$1 default=$2 hint reply
  if [[ $default == y ]]; then hint="[Y/n]"; else hint="[y/N]"; fi
  while true; do
    printf '%s %s ' "$prompt" "$hint"
    read_tty reply
    reply=${reply:-$default}
    case "${reply,,}" in
      y|yes) return 0 ;;
      n|no)  return 1 ;;
      *)     echo "    Please answer y or n." ;;
    esac
  done
}

# ---------------------------------------------------------------------------
# State and backups
# ---------------------------------------------------------------------------
state_set() {
  local key=$1 value=$2
  mkdir -p "$STATE_DIR"
  touch "$STATE_FILE"
  grep -v "^${key}=" "$STATE_FILE" > "${STATE_FILE}.tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "${STATE_FILE}.tmp"
  mv "${STATE_FILE}.tmp" "$STATE_FILE"
}

state_get() {
  local key=$1 content
  [[ -f $STATE_FILE ]] || return 0
  content=$(<"$STATE_FILE")
  grep -m1 "^${key}=" <<<"$content" | cut -d= -f2- || true
}

# previous_choice <state key> <default y|n> -- the answer from the last run, so
# that re-running the script to change one setting keeps the others as they were.
previous_choice() {
  case "$(state_get "$1")" in
    1) echo y ;;
    0) echo n ;;
    *) echo "$2" ;;
  esac
}

# backup_file <path> [sudo]
backup_file() {
  local file=$1 use_sudo=${2:-} dest
  [[ -e $file ]] || return 0
  mkdir -p "$BACKUP_DIR"
  dest="${BACKUP_DIR}/$(basename "$file").$(date +%Y%m%d-%H%M%S).bak"
  if [[ -n $use_sudo ]]; then
    sudo cp -a "$file" "$dest"
    sudo chown "${USER_NAME}:" "$dest"
  else
    cp -a "$file" "$dest"
  fi
  info "Backed up ${file} to ${dest}"
}

# remove_block <file> [sudo] -- removes the section between our marker comments
remove_block() {
  local file=$1 use_sudo=${2:-} tmp
  [[ -f $file ]] || return 0
  tmp=$(mktemp)
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" \
    '$0==b {skip=1; next} $0==e {skip=0; next} !skip' "$file" > "$tmp"
  if [[ -n $use_sudo ]]; then
    # shellcheck disable=SC2024  # the temp file is ours; only the write needs sudo
    sudo tee "$file" < "$tmp" > /dev/null
  else
    cat "$tmp" > "$file"
  fi
  rm -f "$tmp"
}

# write_cmdline <line> -- rewrite cmdline.txt, keeping whether it ended with a newline
write_cmdline() {
  local ending=""
  if [[ -z $(tail -c1 "$CMDLINE_FILE") ]]; then
    ending=$'\n'
  fi
  printf '%s%s' "$1" "$ending" | sudo tee "$CMDLINE_FILE" > /dev/null
}

# Was ~/.asoundrc written by this script?
asoundrc_is_ours() {
  local first=""
  [[ -f $ASOUNDRC ]] || return 1
  IFS= read -r first < "$ASOUNDRC" || true
  [[ $first == "${ASOUND_HEADER}"* ]]
}

package_installed() {
  local status
  status=$(dpkg-query -W -f='${Status}' "$1" 2>/dev/null || true)
  [[ $status == "install ok installed" ]]
}

# ---------------------------------------------------------------------------
# Detection
# ---------------------------------------------------------------------------
detect_display_device() {
  local link target card driver
  for link in /dev/dri/by-path/*-card; do
    [[ -e $link ]] || continue
    target=$(readlink -f "$link")
    card=$(basename "$target")
    driver=$(basename "$(readlink -f "/sys/class/drm/${card}/device/driver" 2>/dev/null)" 2>/dev/null || true)
    if [[ $driver == "vc4-drm" ]]; then
      printf '%s' "$link"
      return 0
    fi
  done
  # Fallback: the Pi 5 display controller is normally called platform-axi:gpu-card
  for link in /dev/dri/by-path/*gpu-card; do
    if [[ -e $link ]]; then
      printf '%s' "$link"
      return 0
    fi
  done
  return 1
}

hdmi_connected() {
  local connector=$1 f
  for f in /sys/class/drm/card*-"${connector}"/status; do
    if [[ -r $f ]] && [[ $(<"$f") == "connected" ]]; then
      return 0
    fi
  done
  return 1
}

# Is the desktop version of Raspberry Pi OS installed? Still true after we've
# switched the Pi to boot to the console, because the display manager remains.
desktop_installed() {
  [[ $(systemctl get-default 2>/dev/null || true) == "graphical.target" ]] \
    || [[ -e /etc/systemd/system/display-manager.service ]]
}

# How the Pi currently boots, using raspi-config's names:
#   B1 console, B2 console with auto-login, B3 desktop, B4 desktop with auto-login
current_boot_behaviour() {
  if [[ $(systemctl get-default 2>/dev/null || true) == "graphical.target" ]]; then
    if grep -qs '^autologin-user=' "$LIGHTDM_CONF"; then echo B4; else echo B3; fi
  else
    if [[ -f $AUTOLOGIN_DROPIN ]]; then echo B2; else echo B1; fi
  fi
}

boot_behaviour_name() {
  case "$1" in
    B1) echo "console login" ;;
    B2) echo "console with automatic login" ;;
    B3) echo "desktop" ;;
    B4) echo "desktop with automatic login" ;;
    *)  echo "unknown" ;;
  esac
}

virtualhere_installed() {
  local units
  units=$(systemctl list-unit-files 2>/dev/null || true)
  grep -qi virtualhere <<<"$units"
}

audio_server_present() {
  if pgrep -x pipewire > /dev/null 2>&1 || pgrep -x pulseaudio > /dev/null 2>&1; then
    return 0
  fi
  if package_installed pipewire-pulse || package_installed pulseaudio; then
    return 0
  fi
  return 1
}

# ---------------------------------------------------------------------------
# Pre-flight checks
# ---------------------------------------------------------------------------
check_failed() {
  if (( FORCE )); then
    warn "$* (continuing because --force was used)"
  else
    die "$* Use --force to continue anyway (unsupported)."
  fi
}

preflight() {
  step "Checking your system"

  if [[ $EUID -eq 0 ]]; then
    die "Please run this script as your normal user (without sudo). It will ask for your password when needed."
  fi
  command -v sudo > /dev/null 2>&1 || die "sudo is not installed."
  info "Some steps need administrator access, so you may be asked for your password."
  # Only prompt for a password if sudo actually needs one.
  sudo -n true 2>/dev/null || sudo -v || die "Could not get administrator access."
  ( while true; do sudo -n true; sleep 50; kill -0 "$$" 2>/dev/null || exit; done ) 2>/dev/null &
  SUDO_KEEPALIVE_PID=$!

  # Hardware
  local model=""
  if [[ -r /proc/device-tree/model ]]; then
    model=$(tr -d '\0' < /proc/device-tree/model)
  fi
  if [[ $model == *"Raspberry Pi 5"* || $model == *"Raspberry Pi 500"* || $model == *"Compute Module 5"* ]]; then
    ok "Hardware: ${model}"
  else
    check_failed "This script supports the Raspberry Pi 5 only (detected: ${model:-unknown})."
  fi

  # Architecture
  local arch
  arch=$(dpkg --print-architecture)
  if [[ $arch == "arm64" ]]; then
    ok "64-bit operating system"
  else
    check_failed "A 64-bit operating system is required (detected: ${arch})."
  fi

  # OS version
  # shellcheck disable=SC1091
  OS_CODENAME=$(. /etc/os-release && printf '%s' "${VERSION_CODENAME:-unknown}")
  if [[ $OS_CODENAME == "trixie" ]]; then
    ok "Raspberry Pi OS (Trixie)"
  else
    check_failed "This script is written for Raspberry Pi OS based on Trixie (detected: ${OS_CODENAME})."
  fi

  # Lite vs desktop
  if desktop_installed; then
    IS_DESKTOP=1
    ok "Raspberry Pi OS with desktop"
  else
    ok "Raspberry Pi OS Lite"
  fi

  # Display controller
  if DISPLAY_DEVICE=$(detect_display_device); then
    ok "Display controller: ${DISPLAY_DEVICE}"
  else
    check_failed "Could not find the Pi's display controller under /dev/dri/by-path."
    DISPLAY_DEVICE="/dev/dri/by-path/platform-axi:gpu-card"
  fi

  # HDMI port
  if hdmi_connected HDMI-A-1; then
    HDMI_PORT=0
    ok "TV detected on HDMI 0 (the port next to the USB-C power socket)"
  elif hdmi_connected HDMI-A-2; then
    HDMI_PORT=1
    ok "TV detected on HDMI 1"
  else
    warn "No TV detected on either HDMI port. Is the TV switched on?"
    printf '    Which HDMI port will the TV use? 0 = next to the power socket, 1 = the other one [0]: '
    local reply
    read_tty reply
    if [[ $reply == "1" ]]; then HDMI_PORT=1; else HDMI_PORT=0; fi
  fi
  if ! grep -q "vc4hdmi${HDMI_PORT}" /proc/asound/cards 2>/dev/null; then
    warn "HDMI audio device vc4hdmi${HDMI_PORT} was not found. Audio may not work until the TV is connected and the Pi is rebooted."
  fi

  # Network: ask the kernel which interface it would use to reach the internet,
  # which picks the right one when both Ethernet and Wi-Fi are connected.
  local iface speed duplex
  iface=$(ip route get 1.1.1.1 2>/dev/null \
    | awk '{for (i = 1; i < NF; i++) if ($i == "dev") {print $(i + 1); exit}}' || true)
  if [[ -z $iface ]]; then
    iface=$(ip -o route show default 2>/dev/null \
      | awk '{for (i = 1; i < NF; i++) if ($i == "dev") {print $(i + 1); exit}}' || true)
  fi
  NET_IFACE=$iface
  if [[ -z $iface ]]; then
    die "No network connection detected. This script needs internet access."
  elif [[ -d /sys/class/net/${iface}/wireless || $iface == wl* ]]; then
    ON_WIFI=1
    warn "You're connected over Wi-Fi (${iface}). Wired Ethernet is strongly recommended for streaming."
  else
    speed=$(cat "/sys/class/net/${iface}/speed" 2>/dev/null || true)
    duplex=$(cat "/sys/class/net/${iface}/duplex" 2>/dev/null || true)
    if [[ $speed =~ ^[0-9]+$ ]] && (( speed >= 1000 )) && [[ $duplex == "full" ]]; then
      ok "Wired network: ${speed} Mb/s, full duplex"
    else
      warn "Your wired connection is running at ${speed:-unknown} Mb/s, ${duplex:-unknown} duplex."
      warn "Gigabit (1000 Mb/s, full duplex) is expected. Check the cable and your router or switch."
    fi
  fi

  # Audio server (the desktop version uses PipeWire)
  if audio_server_present; then
    HAS_AUDIO_SERVER=1
  fi
}

# ---------------------------------------------------------------------------
# Questions
# ---------------------------------------------------------------------------
ask_questions() {
  step "Setup options"
  if [[ -f $STATE_FILE ]]; then
    info "The defaults below are the answers you gave last time."
  fi

  if (( IS_DESKTOP )); then
    echo "    This Pi boots to the desktop. For the best performance, and for HDR, Moonlight"
    echo "    can start on its own instead of the desktop. The desktop stays installed, and"
    echo "    uninstalling this setup switches the Pi back to booting to the desktop."
    if ask_yes_no "    Boot straight into Moonlight instead of the desktop? (recommended)" \
        "$(previous_choice autostart y)"; then
      OPT_AUTOSTART=1
    fi
  else
    if ask_yes_no "    Start Moonlight automatically when the Pi boots? (recommended)" \
        "$(previous_choice autostart y)"; then
      OPT_AUTOSTART=1
    fi
  fi

  # When Moonlight runs from the desktop, the desktop's audio server handles
  # the speakers. When it runs on its own, it talks to the HDMI audio directly.
  if (( HAS_AUDIO_SERVER )) && (( ! OPT_AUTOSTART )); then
    AUDIO_MODE="system"
    info "Audio will be handled by the desktop. To use surround sound, choose 5.1 or 7.1"
    info "for the HDMI output in the desktop's sound settings."
  fi

  if [[ $AUDIO_MODE != "system" ]]; then
    echo "    Which speaker setup do you have?"
    echo "      1) Stereo (TV speakers, soundbar or headphones)"
    echo "      2) 5.1 surround"
    echo "      3) 7.1 surround"
    local choice default_choice=1
    case "$(state_get audio_mode)" in
      5.1) default_choice=2 ;;
      7.1) default_choice=3 ;;
    esac
    while true; do
      printf '    Choose 1, 2 or 3 [%s]: ' "$default_choice"
      read_tty choice
      case "${choice:-$default_choice}" in
        1) AUDIO_MODE="stereo"; break ;;
        2) AUDIO_MODE="5.1"; break ;;
        3)
          AUDIO_MODE="7.1"
          echo
          warn "7.1 audio setup is experimental and hasn't been fully tested."
          warn "If any speakers play the wrong channel, or you run into other problems,"
          warn "please report it on GitHub: ${ISSUES_URL}"
          echo
          break
          ;;
        *) echo "    Please enter 1, 2 or 3." ;;
      esac
    done
  fi

  if ask_yes_no "    Hide boot messages for a cleaner startup? (recommended)" \
      "$(previous_choice quiet_boot y)"; then
    OPT_QUIET_BOOT=1
  fi
  echo "    When the Pi is switched off (for example with its power button), the game keeps"
  echo "    running on your PC and the PC can stay stuck on the stream until it's quit."
  if ask_yes_no "    Quit the running game on your PC when the Pi shuts down? (recommended)" \
      "$(previous_choice quit_on_shutdown y)"; then
    OPT_QUIT_ON_SHUTDOWN=1
  fi

  # Wi-Fi power saving: only asked while on Wi-Fi. Otherwise keep the last answer,
  # so plugging in Ethernet for one run doesn't undo it.
  if (( ON_WIFI )) && systemctl is-active --quiet NetworkManager 2>/dev/null; then
    echo "    Wi-Fi power saving makes the Pi's Wi-Fi doze between packets, which causes"
    echo "    stutter and lag spikes when streaming."
    if ask_yes_no "    Turn off Wi-Fi power saving? (recommended on Wi-Fi)" \
        "$(previous_choice wifi_powersave_off y)"; then
      OPT_WIFI_POWERSAVE_OFF=1
    fi
  elif [[ -f $NM_WIFI_CONF ]]; then
    OPT_WIFI_POWERSAVE_OFF=1
  fi

  if command -v tailscale > /dev/null 2>&1; then
    info "Tailscale is already installed. Skipping that question."
  elif ask_yes_no "    Install Tailscale, to stream when you're away from home?" n; then
    OPT_TAILSCALE=1
  fi
  if virtualhere_installed; then
    info "VirtualHere is already installed. Skipping that question."
  elif ask_yes_no "    Install VirtualHere, to share USB devices plugged into the Pi with your PC?" n; then
    OPT_VIRTUALHERE=1
  fi

  step "Summary"
  info "Moonlight:        install the official moonlight-qt package"
  case "$AUDIO_MODE" in
    system) info "Audio:            handled by the desktop's sound settings" ;;
    7.1)    info "Audio:            7.1 surround (experimental), on whichever HDMI port the TV uses" ;;
    *)      info "Audio:            ${AUDIO_MODE}, on whichever HDMI port the TV uses" ;;
  esac
  if (( IS_DESKTOP )); then
    info "Boot into:        $( (( OPT_AUTOSTART )) && echo "Moonlight (desktop still installed)" || echo "the desktop")"
  else
    info "Auto-start:       $( (( OPT_AUTOSTART )) && echo yes || echo no)"
  fi
  info "Hide boot text:   $( (( OPT_QUIET_BOOT )) && echo yes || echo no)"
  info "Quit on shutdown: $( (( OPT_QUIT_ON_SHUTDOWN )) && echo yes || echo no)"
  if (( ON_WIFI || OPT_WIFI_POWERSAVE_OFF )); then
    info "Wi-Fi power save: $( (( OPT_WIFI_POWERSAVE_OFF )) && echo off || echo "left on")"
  fi
  if command -v tailscale > /dev/null 2>&1; then
    info "Tailscale:        already installed"
  else
    info "Tailscale:        $( (( OPT_TAILSCALE )) && echo yes || echo no)"
  fi
  if virtualhere_installed; then
    info "VirtualHere:      already installed"
  else
    info "VirtualHere:      $( (( OPT_VIRTUALHERE )) && echo yes || echo no)"
  fi
  echo
  ask_yes_no "    Go ahead with these settings?" y || die "Cancelled. Nothing was changed."
}

# ---------------------------------------------------------------------------
# Installation steps
# ---------------------------------------------------------------------------
install_base_packages() {
  step "Installing required packages"
  sudo apt-get update
  sudo apt-get install -y curl alsa-utils
  ok "Base packages installed"
}

install_moonlight() {
  step "Installing Moonlight"
  local policy
  policy=$(apt-cache policy moonlight-qt 2>/dev/null || true)
  if grep -q 'Candidate: [0-9]' <<<"$policy"; then
    info "moonlight-qt is available from your existing package sources."
  else
    info "Adding the official Moonlight package repository..."
    curl -1sLf "$MOONLIGHT_REPO_SCRIPT" | distro=raspbian codename="$OS_CODENAME" sudo -E bash
    state_set moonlight_repo_added 1
    sudo apt-get update
  fi
  sudo apt-get install -y moonlight-qt
  ok "Moonlight installed: $(dpkg-query -W -f='${Version}' moonlight-qt)"
}

setup_groups() {
  step "Giving your user access to the display, GPU, input and audio devices"
  sudo usermod -aG video,render,input,audio "$USER_NAME"
  ok "Added ${USER_NAME} to the video, render, input and audio groups"
}

setup_display() {
  step "Configuring the display"
  mkdir -p "$CONFIG_DIR"
  cat > "$EGLFS_CONFIG" <<EOF
{
  "device": "${DISPLAY_DEVICE}"
}
EOF
  ok "Moonlight's interface will use ${DISPLAY_DEVICE}"
}

asoundrc_content() {
  local mode=$1 card="vc4hdmi${2}"
  cat <<EOF
${ASOUND_HEADER} (${mode}, follows the connected HDMI port)
# Re-run moonlight-pi-setup to change this, or run it with --uninstall to remove it.
#
# The HDMI audio device comes from MOONLIGHT_HDMI_CARD (vc4hdmi0 = HDMI 0,
# vc4hdmi1 = HDMI 1), which ~/.bash_profile sets to whichever HDMI port has a
# screen connected each time Moonlight starts. ${card} is used if it isn't set.

pcm.hdmi_out {
  type plug
  slave.pcm {
    @func concat
    strings [ "hdmi:CARD=" { @func getenv vars [ MOONLIGHT_HDMI_CARD ] default "${card}" } ",DEV=0" ]
  }
}

ctl.!default {
  type hw
  card { @func getenv vars [ MOONLIGHT_HDMI_CARD ] default "${card}" }
}
EOF

  case "$mode" in
    stereo)
      cat <<'EOF'

pcm.!default {
  type plug
  slave.pcm "hdmi_out"
}
EOF
      ;;
    5.1)
      cat <<'EOF'

# The Pi's HDMI output expects 5.1 channels in the order FL FR LFE FC RL RR,
# but Linux programs send them as FL FR RL RR FC LFE. This reorders them.
pcm.hdmi_surround {
  type route
  slave.pcm "hdmi_out"
  slave.channels 6
  ttable.0.0 1   # Front left
  ttable.1.1 1   # Front right
  ttable.2.4 1   # Surround left
  ttable.3.5 1   # Surround right
  ttable.4.3 1   # Centre
  ttable.5.2 1   # LFE (subwoofer)
}

pcm.!default {
  type plug
  slave.pcm "hdmi_surround"
}

# Some programs ask for "surround51" directly when they want 5.1.
pcm.!surround51 {
  type plug
  slave.pcm "hdmi_surround"
}
EOF
      ;;
    7.1)
      cat <<'EOF'

# EXPERIMENTAL. The Pi's HDMI output expects 7.1 channels in the order
# FL FR LFE FC RL RR RLC RRC, but Linux programs send them as
# FL FR RL RR FC LFE SL SR. This reorders them.
# If your side and back speakers are swapped, swap the targets of the
# "Back" lines (6, 7) with the "Side" lines (4, 5) below.
pcm.hdmi_surround {
  type route
  slave.pcm "hdmi_out"
  slave.channels 8
  ttable.0.0 1   # Front left
  ttable.1.1 1   # Front right
  ttable.2.6 1   # Back left
  ttable.3.7 1   # Back right
  ttable.4.3 1   # Centre
  ttable.5.2 1   # LFE (subwoofer)
  ttable.6.4 1   # Side left
  ttable.7.5 1   # Side right
}

pcm.!default {
  type plug
  slave.pcm "hdmi_surround"
}

# Some programs ask for "surround51" or "surround71" directly.
pcm.!surround51 {
  type plug
  slave.pcm "hdmi_surround"
}
pcm.!surround71 {
  type plug
  slave.pcm "hdmi_surround"
}
EOF
      ;;
  esac
}

# Remove our ~/.asoundrc and put back the user's original, if they had one.
remove_asoundrc() {
  asoundrc_is_ours || return 0
  rm -f "$ASOUNDRC"
  local original
  original=$(state_get asoundrc_original)
  if [[ -n $original && -f $original ]]; then
    cp -a "$original" "$ASOUNDRC"
    ok "Restored your original ${ASOUNDRC}"
  else
    ok "Removed ${ASOUNDRC}"
  fi
}

setup_audio() {
  if [[ $AUDIO_MODE == "system" ]]; then
    # An earlier run may have written ~/.asoundrc. Left in place, it would take
    # the HDMI audio away from the desktop's audio server.
    if asoundrc_is_ours; then
      step "Handing audio back to the desktop"
      remove_asoundrc
    fi
    return 0
  fi
  step "Configuring ${AUDIO_MODE} audio"

  if [[ -f $ASOUNDRC ]] && ! asoundrc_is_ours; then
    # A file we didn't create: keep a copy so --uninstall can put it back.
    mkdir -p "$BACKUP_DIR"
    local dest="${BACKUP_DIR}/asoundrc.original"
    if [[ ! -f $dest ]]; then
      cp -a "$ASOUNDRC" "$dest"
      state_set asoundrc_original "$dest"
      info "Backed up your existing ${ASOUNDRC} to ${dest}"
    else
      backup_file "$ASOUNDRC"
    fi
  fi

  asoundrc_content "$AUDIO_MODE" "$HDMI_PORT" > "$ASOUNDRC"
  ok "Wrote ${ASOUNDRC}"

  local channels=2
  [[ $AUDIO_MODE == "5.1" ]] && channels=6
  [[ $AUDIO_MODE == "7.1" ]] && channels=8

  if (( HAS_AUDIO_SERVER )); then
    # The desktop's audio server may be using the HDMI audio right now.
    info "To check your speakers, run this after rebooting (each speaker announces itself):"
    info "  speaker-test -c ${channels} -t wav -l 1"
    return 0
  fi

  echo
  info "You can play a speaker test now. Each speaker will announce its position."
  info "Make sure the TV (and receiver, if you have one) is on."
  if ask_yes_no "    Play a speaker test now?" y; then
    if MOONLIGHT_HDMI_CARD="vc4hdmi${HDMI_PORT}" speaker-test -D default -c "$channels" -t wav -l 1; then
      if ask_yes_no "    Did each announcement come from the correct speaker?" y; then
        ok "Speaker test passed"
      else
        warn "Speakers are playing the wrong channels."
        warn "Please report this, with your TV/receiver model, at: ${ISSUES_URL}"
      fi
    else
      warn "The speaker test failed."
      if (( channels > 2 )); then
        warn "Your TV may only accept stereo from the Pi. For surround sound through a TV"
        warn "to a receiver or soundbar, the TV needs eARC, or connect the Pi to the"
        warn "receiver directly. You can re-run this script and choose Stereo."
      fi
    fi
  fi
}

setup_network() {
  step "Tuning the network for streaming"
  printf '%s\n%s\n' \
    "# Added by moonlight-pi-setup: allow larger UDP receive buffers for game streaming" \
    "net.core.rmem_max=33554432" | sudo tee "$SYSCTL_FILE" > /dev/null
  sudo sysctl -p "$SYSCTL_FILE" > /dev/null
  ok "Raised the network receive buffer limit (net.core.rmem_max)"

  if (( OPT_WIFI_POWERSAVE_OFF )); then
    printf '%s\n%s\n%s\n' \
      "# Added by moonlight-pi-setup: Wi-Fi power saving causes lag spikes when streaming" \
      "[connection]" \
      "wifi.powersave = 2" | sudo tee "$NM_WIFI_CONF" > /dev/null
    sudo systemctl reload NetworkManager 2>/dev/null || true
    # The setting above applies from the next reconnect; this applies it right away.
    if (( ON_WIFI )) && command -v iw > /dev/null 2>&1; then
      sudo iw dev "$NET_IFACE" set power_save off 2>/dev/null || true
    fi
    ok "Turned off Wi-Fi power saving"
  else
    remove_wifi_powersave
  fi
}

remove_wifi_powersave() {
  [[ -f $NM_WIFI_CONF ]] || return 0
  sudo rm -f "$NM_WIFI_CONF"
  sudo systemctl reload NetworkManager 2>/dev/null || true
  ok "Turned Wi-Fi power saving back on (takes effect after a reboot)"
}

setup_autologin() {
  local current original
  current=$(current_boot_behaviour)
  original=$(state_get original_boot_behaviour)

  # Remember how the Pi booted before this script first changed it, so that
  # --uninstall (or turning auto-start off) can put it back.
  if [[ -z $original ]]; then
    if [[ $(state_get autologin_enabled_by_script) == 1 ]]; then
      original=B1   # installed by an older version of this script (Lite only)
    else
      original=$current
    fi
    state_set original_boot_behaviour "$original"
  fi

  if ! command -v raspi-config > /dev/null 2>&1; then
    if (( OPT_AUTOSTART )); then
      warn "raspi-config not found, so automatic login could not be enabled."
      warn "Moonlight will still start when you log in on the TV."
    fi
    return 0
  fi

  if (( OPT_AUTOSTART )); then
    step "Setting up auto-start"
    if [[ $current == B2 ]]; then
      info "The Pi already boots to the console with automatic login."
    else
      sudo raspi-config nonint do_boot_behaviour B2
      ok "The Pi will now boot to the console with automatic login (was: $(boot_behaviour_name "$current"))"
    fi
    if [[ $original != B2 ]]; then
      state_set autologin_enabled_by_script 1
    fi
    if (( IS_DESKTOP )); then
      info "The desktop is still installed. To open it, quit Moonlight, press a key, then"
      info "type: sudo systemctl start display-manager"
    fi
  elif [[ $(state_get autologin_enabled_by_script) == 1 ]]; then
    # Auto-start was turned on by an earlier run and has now been turned off.
    step "Turning off auto-start"
    if [[ $current != "$original" ]]; then
      sudo raspi-config nonint do_boot_behaviour "$original"
    fi
    state_set autologin_enabled_by_script 0
    ok "The Pi will boot to the $(boot_behaviour_name "$original") again"
  fi
}

setup_bash_profile() {
  step "Updating ${BASH_PROFILE}"
  local created
  created=$(state_get created_bash_profile)
  if [[ ! -f $BASH_PROFILE ]]; then
    touch "$BASH_PROFILE"
    created=1
    state_set created_bash_profile 1
  else
    backup_file "$BASH_PROFILE"
  fi

  remove_block "$BASH_PROFILE"

  # Warn about older manual Moonlight settings outside our section.
  local leftovers
  leftovers=$(grep -nE 'QT_QPA_EGLFS_KMS_CONFIG|AUDIODEV|VK_DRIVER_FILES|PYROWAVE_PRECISION|moonlight' "$BASH_PROFILE" || true)
  if [[ -n $leftovers ]]; then
    warn "${BASH_PROFILE} already contains Moonlight-related lines that this script didn't add:"
    while IFS= read -r line; do info "  ${line}"; done <<<"$leftovers"
    warn "They may conflict with the new settings. Consider removing them."
  fi

  {
    echo "$MARK_BEGIN"
    echo "# Managed by moonlight-pi-setup. Re-run the script to change these settings,"
    echo "# or run it with --uninstall to remove them."
    if [[ $created == 1 ]]; then
      # shellcheck disable=SC2016
      echo '[ -f "$HOME/.profile" ] && . "$HOME/.profile"'
    fi
    # shellcheck disable=SC2016
    echo 'export QT_QPA_EGLFS_KMS_CONFIG="$HOME/.config/moonlight-pi-setup/eglfs.json"'
    if [[ $AUDIO_MODE != "system" ]]; then
      echo 'export AUDIODEV=default'
      cat <<EOF
# Send audio to whichever HDMI port has a screen connected (HDMI 0 is checked
# first). Falls back to HDMI ${HDMI_PORT}, the port used during setup.
moonlight_hdmi_card() {
  for port in 1 2; do
    for status in /sys/class/drm/card*-HDMI-A-\$port/status; do
      if [ "\$(cat "\$status" 2>/dev/null)" = "connected" ]; then
        echo "vc4hdmi\$((port - 1))"; return
      fi
    done
  done
  echo "vc4hdmi${HDMI_PORT}"
}
export MOONLIGHT_HDMI_CARD="\$(moonlight_hdmi_card)"
EOF
      # Use the ALSA settings above even if PipeWire (desktop version) is installed.
      echo 'export SDL_AUDIODRIVER=alsa'
    fi
    if (( OPT_AUTOSTART )); then
      cat <<'EOF'
# Start Moonlight on the TV (tty1 only, so SSH logins are not affected)
if [ "$(tty)" = "/dev/tty1" ]; then
  while true; do
    if command -v moonlight_hdmi_card > /dev/null 2>&1; then
      export MOONLIGHT_HDMI_CARD="$(moonlight_hdmi_card)"
    fi
    moonlight-qt > /tmp/moonlight.log 2>&1
    echo "Moonlight closed. Press any key within 5 seconds for a command line..."
    if read -r -t 5 -n 1; then
      echo
      echo "Type 'moonlight-qt' to start Moonlight again, or 'sudo reboot' to restart the Pi."
      if [ -e /etc/systemd/system/display-manager.service ]; then
        echo "To open the desktop, type: sudo systemctl start display-manager"
      fi
      break
    fi
  done
fi
EOF
    fi
    echo "$MARK_END"
  } >> "$BASH_PROFILE"
  ok "Saved Moonlight settings$( (( OPT_AUTOSTART )) && echo " and auto-start")"
}

quiet_boot_enabled() {
  [[ -n $(state_get quiet_tokens_added) ]] \
    || { [[ -f $CONFIG_TXT ]] && grep -qF "$MARK_BEGIN" "$CONFIG_TXT"; }
}

# Undo setup_quiet_boot, removing only the boot options this script added.
remove_quiet_boot() {
  local tokens token line
  tokens=$(state_get quiet_tokens_added)
  if [[ -n $tokens && -f $CMDLINE_FILE ]]; then
    backup_file "$CMDLINE_FILE" sudo
    line=$(head -n1 "$CMDLINE_FILE")
    for token in $tokens; do
      line=$(sed -E "s/(^| )${token//./\\.}( |$)/ /g" <<<"$line")
    done
    line=$(sed -E 's/ +/ /g; s/^ //; s/ $//' <<<"$line")
    write_cmdline "$line"
    state_set quiet_tokens_added ""
    ok "Restored boot messages"
  fi
  if [[ -f $CONFIG_TXT ]] && grep -qF "$MARK_BEGIN" "$CONFIG_TXT"; then
    backup_file "$CONFIG_TXT" sudo
    remove_block "$CONFIG_TXT" sudo
    ok "Restored the boot splash screen"
  fi
}

setup_quiet_boot() {
  if (( ! OPT_QUIET_BOOT )); then
    if quiet_boot_enabled; then
      step "Showing boot messages again"
      remove_quiet_boot
    fi
    return 0
  fi
  step "Hiding boot messages"
  if [[ ! -f $CMDLINE_FILE || ! -f $CONFIG_TXT ]]; then
    warn "Could not find ${CMDLINE_FILE} or ${CONFIG_TXT}. Skipping."
    return 0
  fi

  backup_file "$CMDLINE_FILE" sudo
  local line token added=()
  line=$(head -n1 "$CMDLINE_FILE")
  for token in "${QUIET_TOKENS[@]}"; do
    if [[ " ${line} " != *" ${token} "* ]]; then
      line="${line} ${token}"
      added+=("$token")
    fi
  done
  write_cmdline "$line"
  local previous all
  previous=$(state_get quiet_tokens_added)
  # shellcheck disable=SC2086  # $previous is a space-separated list on purpose
  all=$(printf '%s\n' $previous "${added[@]}" | awk 'NF && !seen[$0]++' | xargs)
  state_set quiet_tokens_added "$all"

  backup_file "$CONFIG_TXT" sudo
  remove_block "$CONFIG_TXT" sudo
  printf '%s\n[all]\ndisable_splash=1\n%s\n' "$MARK_BEGIN" "$MARK_END" | sudo tee -a "$CONFIG_TXT" > /dev/null
  ok "Boot messages and the splash screen will be hidden"
}

# Remove the quit-on-shutdown service. The helper goes first: stopping the
# service runs it, which would quit a game that's being played right now.
remove_quit_on_shutdown() {
  [[ -f $QUIT_SERVICE || -f $QUIT_HELPER ]] || return 0
  if [[ -f $QUIT_HELPER ]] && grep -q "moonlight-pi-setup" "$QUIT_HELPER"; then
    sudo rm -f "$QUIT_HELPER"
  fi
  if [[ -f $QUIT_SERVICE ]]; then
    sudo systemctl disable --now "$QUIT_SERVICE_NAME" > /dev/null 2>&1 || true
    sudo rm -f "$QUIT_SERVICE"
    sudo systemctl daemon-reload
    sudo systemctl reset-failed "$QUIT_SERVICE_NAME" > /dev/null 2>&1 || true
    ok "Removed the quit-on-shutdown service"
  fi
}

setup_quit_on_shutdown() {
  if (( ! OPT_QUIT_ON_SHUTDOWN )); then
    if [[ -f $QUIT_SERVICE ]]; then
      step "Turning off 'quit game on shutdown'"
      remove_quit_on_shutdown
    fi
    return 0
  fi
  step "Setting up 'quit game on shutdown'"

  sudo tee "$QUIT_HELPER" > /dev/null <<'EOF'
#!/usr/bin/env bash
# Installed by moonlight-pi-setup.
# Asks every paired Moonlight host to quit its running app. Hosts with nothing
# running are unaffected. Run automatically when the Pi shuts down.
CONF="$HOME/.config/Moonlight Game Streaming Project/Moonlight.conf"
[ -f "$CONF" ] || exit 0
export QT_QPA_PLATFORM=offscreen
# Moonlight lists every PC it has seen on the network, but only paired PCs
# have a saved server certificate (srvcert). Unpaired PCs can't be asked to quit.
paired_hosts() {
  awk '
    /^[0-9]+\\hostname=/ { n=$0; sub(/\\.*/, "", n); v=$0; sub(/^[^=]*=/, "", v); host[n]=v }
    /^[0-9]+\\srvcert=/  { n=$0; sub(/\\.*/, "", n); v=$0; sub(/^[^=]*=/, "", v); cert[n]=v }
    END { for (n in host) if (host[n] != "" && cert[n] != "" && cert[n] != "@ByteArray()") print host[n] }
  ' "$CONF" | sort -u
}
paired_hosts | while read -r host; do
  echo "Quitting any running app on: $host"
  timeout 10 moonlight-qt quit "$host" > /dev/null 2>&1 \
    && echo "  done" || echo "  (no response from $host)"
done
exit 0
EOF
  sudo chmod 755 "$QUIT_HELPER"

  sudo tee "$QUIT_SERVICE" > /dev/null <<EOF
# Installed by moonlight-pi-setup.
[Unit]
Description=Tell Moonlight hosts to quit the running app when the Pi shuts down
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
User=${USER_NAME}
Environment=HOME=${HOME}
ExecStart=/bin/true
ExecStop=${QUIT_HELPER}
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF
  sudo systemctl daemon-reload
  sudo systemctl enable --now "$QUIT_SERVICE_NAME"
  ok "The running game on your PC will be quit when the Pi shuts down"
  info "Note: this closes the game, so save before switching the Pi off."
  info "Test it any time with: ${QUIT_HELPER}"
}

install_tailscale() {
  (( OPT_TAILSCALE )) || return 0
  step "Installing Tailscale"
  if command -v tailscale > /dev/null 2>&1; then
    info "Tailscale is already installed."
  else
    if ! curl -fsSL "$TAILSCALE_INSTALL_SCRIPT" | sh; then
      warn "Tailscale could not be installed. You can install it later from https://tailscale.com/download"
      return 0
    fi
    state_set tailscale_installed_by_script 1
  fi
  echo
  info "Starting Tailscale. It will show a link: open it on your phone or PC to sign in."
  if sudo tailscale up; then
    ok "Tailscale is connected. Install Tailscale on your gaming PC too, signed in to the same account."
  else
    warn "Tailscale didn't finish signing in. You can run 'sudo tailscale up' later."
  fi
}

install_virtualhere() {
  (( OPT_VIRTUALHERE )) || return 0
  step "Installing the VirtualHere USB server"
  if virtualhere_installed; then
    info "VirtualHere is already installed."
    return 0
  fi
  info "Downloading VirtualHere's official installer. The free version shares one USB"
  info "device at a time. Sharing more needs a licence from virtualhere.com."
  if curl -fsSL "$VH_INSTALL_SCRIPT" | sudo sh; then
    state_set virtualhere_installed_by_script 1
    ok "VirtualHere server installed and set to start at boot"
  else
    warn "VirtualHere could not be installed. See https://github.com/virtualhere/script"
  fi
}

# Keep a copy of this script so --uninstall works even if it was run with curl | bash.
save_script_copy() {
  local src="${BASH_SOURCE[0]:-}"
  if [[ -n $src && -f $src ]]; then
    if [[ $(readlink -f "$src") != $(readlink -f "$SAVED_SCRIPT" 2>/dev/null || true) ]]; then
      cp "$src" "$SAVED_SCRIPT"
    fi
  elif ! curl -fsSL "$RAW_SCRIPT_URL" -o "$SAVED_SCRIPT"; then
    warn "Could not save a copy of this script for uninstalling. Download it again from ${REPO_URL} if needed."
    return 0
  fi
  chmod +x "$SAVED_SCRIPT"
}

finish_install() {
  save_script_copy
  state_set version "$SCRIPT_VERSION"
  state_set audio_mode "$AUDIO_MODE"
  state_set hdmi_port "$HDMI_PORT"
  state_set autostart "$OPT_AUTOSTART"
  state_set quiet_boot "$OPT_QUIET_BOOT"
  state_set quit_on_shutdown "$OPT_QUIT_ON_SHUTDOWN"
  state_set wifi_powersave_off "$OPT_WIFI_POWERSAVE_OFF"

  step "All done"
  info "Recommended Moonlight settings (in Moonlight's settings screen):"
  info "  - Video codec:  HEVC (H.265)"
  info "  - Resolution:   match your TV, or 1440p / 1080p"
  info "  - Frame rate:   60 FPS"
  info "  - Bitrate:      around 50-100 Mbit/s on wired Ethernet"
  info "  - V-Sync:       on (off saves a few ms, but may cause tearing)"
  case "$AUDIO_MODE" in
    5.1) info "  - Audio:        5.1 surround (also set Windows to 5.1 for the stream)" ;;
    7.1) info "  - Audio:        7.1 surround (also set Windows to 7.1 for the stream)" ;;
    *)   info "  - Audio:        Stereo" ;;
  esac
  echo
  if (( IS_DESKTOP )) && (( ! OPT_AUTOSTART )); then
    info "Open Moonlight from the desktop's applications menu (under Games)."
    info "Tip: running Moonlight from the desktop works, but HDR and the lowest latency"
    info "need it to run on its own. Re-run this script to switch at any time."
    echo
  fi
  info "On your gaming PC you need a streaming host: Sunshine, Apollo or Vibepollo."
  if (( OPT_TAILSCALE )); then
    info "Tailscale: install it on your gaming PC too. Away from home, add the PC in"
    info "Moonlight using its Tailscale address (100.x.x.x) and lower the bitrate."
  fi
  if (( OPT_VIRTUALHERE )); then
    info "VirtualHere: install the VirtualHere client on your PC from"
    info "https://www.virtualhere.com/usb_client_software"
  fi
  echo
  info "Moonlight log (after reboot): /tmp/moonlight.log"
  info "This run's log:               ${LOG_FILE}"
  info "To undo these changes:        ${SAVED_SCRIPT} --uninstall"
  echo
  info "A reboot is needed for the new group membership and auto-start to take effect."
  if ask_yes_no "    Reboot now?" y; then
    sudo reboot
  else
    info "Reboot later with: sudo reboot"
  fi
}

# ---------------------------------------------------------------------------
# Uninstall
# ---------------------------------------------------------------------------
do_uninstall() {
  step "Uninstalling moonlight-pi-setup"
  if [[ $EUID -eq 0 ]]; then
    die "Please run --uninstall as your normal user (without sudo)."
  fi
  if [[ ! -f $STATE_FILE ]]; then
    warn "No record of a previous install was found in ${STATE_DIR}."
    ask_yes_no "    Try to remove the settings anyway?" n || exit 0
  fi
  # Only prompt for a password if sudo actually needs one.
  sudo -n true 2>/dev/null || sudo -v || die "Could not get administrator access."

  ask_yes_no "    Remove the settings this script added?" y || exit 0

  # ~/.bash_profile
  if [[ -f $BASH_PROFILE ]]; then
    remove_block "$BASH_PROFILE"
    if [[ $(state_get created_bash_profile) == 1 ]] && ! grep -q '[^[:space:]]' "$BASH_PROFILE"; then
      rm -f "$BASH_PROFILE"
      ok "Removed ${BASH_PROFILE}"
    else
      ok "Removed Moonlight settings from ${BASH_PROFILE}"
    fi
  fi

  # ~/.asoundrc
  remove_asoundrc

  # Display config
  if [[ -d $CONFIG_DIR ]]; then
    rm -rf "$CONFIG_DIR"
    ok "Removed ${CONFIG_DIR}"
  fi

  # Network tuning
  if [[ -f $SYSCTL_FILE ]]; then
    sudo rm -f "$SYSCTL_FILE"
    ok "Removed ${SYSCTL_FILE} (takes effect after a reboot)"
  fi

  # Boot behaviour: put back how the Pi booted before (desktop or console)
  if [[ $(state_get autologin_enabled_by_script) == 1 ]] && command -v raspi-config > /dev/null 2>&1; then
    local original current
    original=$(state_get original_boot_behaviour)
    original=${original:-B1}
    current=$(current_boot_behaviour)
    if [[ $current != "$original" ]]; then
      sudo raspi-config nonint do_boot_behaviour "$original"
    fi
    case "$original" in
      B3|B4) ok "The Pi will boot to the desktop again" ;;
      *)     ok "Turned off automatic console login" ;;
    esac
  fi

  # Wi-Fi power saving
  remove_wifi_powersave

  # Quiet boot
  remove_quiet_boot

  # Quit on shutdown
  remove_quit_on_shutdown

  # Optional software
  if package_installed moonlight-qt && ask_yes_no "    Also uninstall Moonlight?" n; then
    sudo apt-get remove -y moonlight-qt
    if [[ $(state_get moonlight_repo_added) == 1 ]]; then
      sudo rm -f /etc/apt/sources.list.d/*moonlight-game-streaming*
      sudo rm -f /usr/share/keyrings/*moonlight-game-streaming*
      ok "Removed the Moonlight package repository"
    fi
  fi
  if [[ $(state_get tailscale_installed_by_script) == 1 ]] && ask_yes_no "    Also uninstall Tailscale?" n; then
    sudo tailscale down || true
    sudo apt-get remove -y tailscale || warn "Could not remove Tailscale."
  fi
  if [[ $(state_get virtualhere_installed_by_script) == 1 ]] && ask_yes_no "    Also uninstall VirtualHere?" n; then
    curl -fsSL "$VH_UNINSTALL_SCRIPT" | sudo sh || warn "Could not remove VirtualHere."
  fi

  rm -f "$STATE_FILE"
  echo
  info "Backups of the files this script changed are kept in: ${BACKUP_DIR}"
  info "Your user was left in the video, render, input and audio groups (this is harmless)."
  if ask_yes_no "    Reboot now to finish?" y; then
    sudo reboot
  fi
}

# ---------------------------------------------------------------------------
# Main
# ---------------------------------------------------------------------------
usage() {
  cat <<EOF
moonlight-pi-setup ${SCRIPT_VERSION}

Sets up a Raspberry Pi 5 running Raspberry Pi OS (64-bit, Trixie; Lite or
desktop) as a Moonlight game-streaming client.

Usage: $0 [option]

  (no option)    Install, or re-run to change your settings
  --uninstall    Undo the changes this script made
  --force        Skip the hardware and OS checks (unsupported)
  --help         Show this help
  --version      Show the version

More information: ${REPO_URL}
EOF
}

main() {
  local mode="install"
  while [[ $# -gt 0 ]]; do
    case "$1" in
      --uninstall) mode="uninstall" ;;
      --force)     FORCE=1 ;;
      --help|-h)   usage; exit 0 ;;
      --version)   echo "$SCRIPT_VERSION"; exit 0 ;;
      *)           usage; exit 1 ;;
    esac
    shift
  done

  mkdir -p "$STATE_DIR"
  LOG_FILE="${STATE_DIR}/${mode}-$(date +%Y%m%d-%H%M%S).log"
  exec > >(tee -a "$LOG_FILE") 2>&1

  printf '%sMoonlight Pi Setup %s%s\n' "$C_BOLD" "$SCRIPT_VERSION" "$C_RESET"

  if [[ $mode == "uninstall" ]]; then
    do_uninstall
    exit 0
  fi

  preflight
  ask_questions
  install_base_packages
  install_moonlight
  setup_groups
  setup_display
  setup_audio
  setup_network
  setup_autologin
  setup_bash_profile
  setup_quiet_boot
  setup_quit_on_shutdown
  install_tailscale
  install_virtualhere
  finish_install
}

# Run main when executed directly or piped into bash (BASH_SOURCE is empty when piped).
if [[ "${BASH_SOURCE[0]:-$0}" == "$0" ]]; then
  main "$@"
fi
