#!/usr/bin/env bash
#
# moonlight-settings: applies the Moonlight Pi settings. The setup script and
# the TV menu both use it, so each setting is changed in one place.
#
# Installed by moonlight-pi-setup at /usr/local/lib/moonlight-pi-setup/moonlight-settings,
# owned by root. A sudoers rule lets the Pi's user run it without a password
# (for the menu), so it only accepts the commands and values below, and never
# runs anything from the user's home folder.
#
# Run as the Pi's user:
#   status                       current settings, one key=value per line
#   speakers stereo|5.1|7.1      write ~/.asoundrc and set Moonlight's audio to match
# Run as root (sudo):
#   init USER                    remember which user the Pi is set up for
#   quit-on-shutdown on|off      quit the game on the PC when the Pi shuts down
#   usb-handoff on|off           share USB devices only while streaming (VirtualHere)
#   quiet-boot on|off            hide boot messages (after a restart)
#   wifi-powersave on|off        Wi-Fi power saving
#   wifi-country XX              Wi-Fi country (two letters)
#   tailscale install|up|down|logout
#   updates check|install        Moonlight and system updates (apt)
#   update-setup                 download the latest moonlight-pi-setup and run it
#
set -Eeuo pipefail
umask 022
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin

RAW_SCRIPT_URL="https://raw.githubusercontent.com/joshmichael/moonlight-pi-setup/main/moonlight-pi-setup.sh"
TAILSCALE_INSTALL_SCRIPT="https://tailscale.com/install.sh"

ROOT_STATE_DIR="/var/lib/moonlight-pi-setup"
ROOT_STATE="${ROOT_STATE_DIR}/state"
BACKUP_DIR="${ROOT_STATE_DIR}/backups"
LOCK_FILE="/run/lock/moonlight-settings.lock"
CMDLINE_FILE="/boot/firmware/cmdline.txt"
CONFIG_TXT="/boot/firmware/config.txt"
NM_WIFI_CONF="/etc/NetworkManager/conf.d/90-moonlight-pi-setup-wifi.conf"
QUIT_HELPER="/usr/local/bin/moonlight-quit-all"
QUIT_SERVICE_NAME="moonlight-quit-on-shutdown.service"
QUIT_SERVICE="/etc/systemd/system/${QUIT_SERVICE_NAME}"
VH_SERVICE_NAME="virtualhere.service"
VH_CONFIG="/usr/local/etc/virtualhere/config.ini"
HANDOFF_HELPER="/usr/local/bin/moonlight-usb-handoff"
HANDOFF_SERVICE_NAME="moonlight-usb-handoff.service"
HANDOFF_SERVICE="/etc/systemd/system/${HANDOFF_SERVICE_NAME}"
COUNTRIES="/usr/share/zoneinfo/iso3166.tab"

MARK_BEGIN="# >>> moonlight-pi-setup >>>"
MARK_END="# <<< moonlight-pi-setup <<<"
ASOUND_HEADER="# Generated by moonlight-pi-setup"
QUIET_TOKENS=(quiet loglevel=3 logo.nologo vt.global_cursor_default=0)

USER_NAME=""
USER_HOME=""

say() { printf '%s\n' "$*"; }
die() { printf 'ERROR: %s\n' "$*" >&2; exit 1; }
trap 'die "Something went wrong (moonlight-settings line ${LINENO})."' ERR

usage() {
  sed -n '/^# Run as the/,/^#$/p' "$0" | sed 's/^# \{0,1\}//'
}

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------
kv_get() {   # kv_get <file> <key>
  [[ -r $1 ]] || return 0
  grep -m1 "^$2=" "$1" | cut -d= -f2- || true
}

root_set() {
  local key=$1 value=$2
  install -d -m 755 "$ROOT_STATE_DIR"
  touch "$ROOT_STATE"
  { grep -v "^${key}=" "$ROOT_STATE" || true; printf '%s=%s\n' "$key" "$value"; } > "${ROOT_STATE}.tmp"
  chmod 644 "${ROOT_STATE}.tmp"
  mv "${ROOT_STATE}.tmp" "$ROOT_STATE"
}

require_root() {
  [[ $EUID -eq 0 ]] || die "This needs administrator access: run it with sudo."
}

# The user the Pi is set up for, recorded by 'init'.
load_user() {
  USER_NAME=$(kv_get "$ROOT_STATE" user)
  [[ -n $USER_NAME ]] || die "The Pi hasn't been set up yet. Run moonlight-pi-setup.sh first."
  USER_HOME=$(getent passwd "$USER_NAME" | cut -d: -f6)
  [[ -n $USER_HOME && -d $USER_HOME ]] || die "Can't find the home folder of ${USER_NAME}."
}

# The user running this (for the commands that run as the user).
load_self() {
  USER_NAME=$(id -un)
  USER_HOME=$(getent passwd "$USER_NAME" | cut -d: -f6)
}

lock() {
  exec 9> "$LOCK_FILE"
  flock -w 600 9 || die "Another settings change is still running."
}

# backup <file>: keep a copy, and only the 5 newest copies of each file.
backup() {
  local file=$1 name
  [[ -f $file ]] || return 0
  install -d -m 700 "$BACKUP_DIR"
  name=$(basename "$file")
  cp -a "$file" "${BACKUP_DIR}/${name}.$(date +%Y%m%d-%H%M%S).bak"
  # shellcheck disable=SC2012  # the names are ours, without spaces
  ls -1t "${BACKUP_DIR}/${name}".*.bak 2> /dev/null | tail -n +6 | xargs -r rm -f --
}

# remove_block <file>: remove the section between our marker comments.
remove_block() {
  local file=$1 tmp
  [[ -f $file ]] || return 0
  tmp=$(mktemp)
  awk -v b="$MARK_BEGIN" -v e="$MARK_END" \
    '$0==b {skip=1; next} $0==e {skip=0; next} !skip' "$file" > "$tmp"
  cat "$tmp" > "$file"
  rm -f "$tmp"
}

# write_cmdline <line>: rewrite cmdline.txt, keeping whether it ended with a newline.
write_cmdline() {
  local ending=""
  if [[ -z $(tail -c1 "$CMDLINE_FILE") ]]; then
    ending=$'\n'
  fi
  printf '%s%s' "$1" "$ending" > "$CMDLINE_FILE"
}

service_enabled() {
  systemctl is-enabled --quiet "$1" 2> /dev/null
}

virtualhere_installed() {
  local units
  units=$(systemctl list-unit-files 2> /dev/null || true)
  grep -qi virtualhere <<<"$units"
}

wifi_ifaces() {
  local d
  for d in /sys/class/net/*/wireless; do
    [[ -e $d ]] && basename "$(dirname "$d")"
  done
  return 0
}

# ---------------------------------------------------------------------------
# status
# ---------------------------------------------------------------------------
cmd_status() {
  if (( EUID == 0 )); then load_user; else load_self; fi
  local speakers=none first="" country
  if [[ -f $USER_HOME/.asoundrc ]]; then
    IFS= read -r first < "$USER_HOME/.asoundrc" || true
    if [[ $first == "${ASOUND_HEADER} ("* ]]; then
      speakers=${first#"${ASOUND_HEADER} ("}
      speakers=${speakers%%,*}
    else
      speakers=custom
    fi
  fi
  country=$(grep -o 'cfg80211.ieee80211_regdom=[A-Z]*' "$CMDLINE_FILE" 2> /dev/null | head -n1 | cut -d= -f2 || true)
  say "speakers=${speakers}"
  say "quit_on_shutdown=$(service_enabled "$QUIT_SERVICE_NAME" && echo 1 || echo 0)"
  say "virtualhere=$(virtualhere_installed && echo 1 || echo 0)"
  say "usb_handoff=$(service_enabled "$HANDOFF_SERVICE_NAME" && echo 1 || echo 0)"
  say "quiet_boot=$(grep -qsF "$MARK_BEGIN" "$CONFIG_TXT" && echo 1 || echo 0)"
  say "wifi=$(compgen -G '/sys/class/net/*/wireless' > /dev/null && echo 1 || echo 0)"
  say "wifi_powersave=$([[ -f $NM_WIFI_CONF ]] && echo 0 || echo 1)"
  say "wifi_country=${country}"
  say "tailscale=$(command -v tailscale > /dev/null && echo 1 || echo 0)"
}

# ---------------------------------------------------------------------------
# init
# ---------------------------------------------------------------------------
cmd_init() {
  local user=${1:-} existing home ustate tokens token kept=()
  if [[ ! $user =~ ^[a-z_][a-z0-9_-]*$ ]] || ! getent passwd "$user" > /dev/null; then
    die "No such user: ${user}"
  fi
  existing=$(kv_get "$ROOT_STATE" user)
  if [[ -n $existing && $existing != "$user" ]]; then
    die "This Pi is set up for ${existing}. Uninstall moonlight-pi-setup first to set it up for another user."
  fi
  root_set user "$user"

  # Older versions of the setup script kept these in the user's state file.
  if [[ -z $(kv_get "$ROOT_STATE" migrated) ]]; then
    home=$(getent passwd "$user" | cut -d: -f6)
    ustate="${home}/.local/share/moonlight-pi-setup/state"
    tokens=$(kv_get "$ustate" quiet_tokens_added)
    for token in $tokens; do
      if [[ " ${QUIET_TOKENS[*]} " == *" ${token} "* ]]; then
        kept+=("$token")
      fi
    done
    root_set quiet_tokens_added "${kept[*]}"
    [[ $(kv_get "$ustate" vh_disabled_by_handoff) == 1 ]] && root_set vh_disabled_by_handoff 1
    [[ $(kv_get "$ustate" tailscale_installed_by_script) == 1 ]] && root_set tailscale_installed_by_script 1
    root_set migrated 1
  fi
  say "Settings helper set up for ${user}"
}

# ---------------------------------------------------------------------------
# speakers (as the user)
# ---------------------------------------------------------------------------
asoundrc_content() {
  local mode=$1 card="vc4hdmi${2}"
  cat <<EOF
${ASOUND_HEADER} (${mode}, follows the connected HDMI port)
# Change this in the TV menu (Settings > Speakers) or by re-running moonlight-pi-setup.
#
# The HDMI audio device comes from MOONLIGHT_HDMI_CARD (vc4hdmi0 = HDMI 0,
# vc4hdmi1 = HDMI 1), which ~/.bash_profile sets to whichever HDMI port has a
# screen connected each time Moonlight starts. ${card} is used if it isn't set.

pcm.hdmi_out {
  type plug
  slave.pcm {
    @func concat
    strings [ "hdmi:CARD=" { @func getenv vars [ MOONLIGHT_HDMI_CARD ] default "${card}" } ",DEV=0" ]
  }
}

ctl.!default {
  type hw
  card { @func getenv vars [ MOONLIGHT_HDMI_CARD ] default "${card}" }
}
EOF

  case "$mode" in
    stereo)
      cat <<'EOF'

pcm.!default {
  type plug
  slave.pcm "hdmi_out"
}
EOF
      ;;
    5.1)
      cat <<'EOF'

# The Pi's HDMI output expects 5.1 channels in the order FL FR LFE FC RL RR,
# but Linux programs send them as FL FR RL RR FC LFE. This reorders them.
pcm.hdmi_surround {
  type route
  slave.pcm "hdmi_out"
  slave.channels 6
  ttable.0.0 1   # Front left
  ttable.1.1 1   # Front right
  ttable.2.4 1   # Surround left
  ttable.3.5 1   # Surround right
  ttable.4.3 1   # Centre
  ttable.5.2 1   # LFE (subwoofer)
}

pcm.!default {
  type plug
  slave.pcm "hdmi_surround"
}

# Some programs ask for "surround51" directly when they want 5.1.
pcm.!surround51 {
  type plug
  slave.pcm "hdmi_surround"
}
EOF
      ;;
    7.1)
      cat <<'EOF'

# EXPERIMENTAL. The Pi's HDMI output expects 7.1 channels in the order
# FL FR LFE FC RL RR RLC RRC, but Linux programs send them as
# FL FR RL RR FC LFE SL SR. This reorders them.
# If your side and back speakers are swapped, swap the targets of the
# "Back" lines (6, 7) with the "Side" lines (4, 5) below.
pcm.hdmi_surround {
  type route
  slave.pcm "hdmi_out"
  slave.channels 8
  ttable.0.0 1   # Front left
  ttable.1.1 1   # Front right
  ttable.2.6 1   # Back left
  ttable.3.7 1   # Back right
  ttable.4.3 1   # Centre
  ttable.5.2 1   # LFE (subwoofer)
  ttable.6.4 1   # Side left
  ttable.7.5 1   # Side right
}

pcm.!default {
  type plug
  slave.pcm "hdmi_surround"
}

# Some programs ask for "surround51" or "surround71" directly.
pcm.!surround51 {
  type plug
  slave.pcm "hdmi_surround"
}
pcm.!surround71 {
  type plug
  slave.pcm "hdmi_surround"
}
EOF
      ;;
  esac
}

# Moonlight's own audio setting (Settings > Audio configuration): audiocfg is
# 0 for stereo, 1 for 5.1 and 2 for 7.1.
set_moonlight_audio() {
  local mode=$1 value conf
  conf="${USER_HOME}/.config/Moonlight Game Streaming Project/Moonlight.conf"
  case "$mode" in
    stereo) value=0 ;;
    5.1) value=1 ;;
    *) value=2 ;;
  esac
  if pgrep -u "$(id -u)" -x moonlight-qt > /dev/null; then
    # Moonlight saves its settings when it closes, which would undo this.
    say "Moonlight is open, so choose the same audio setting in Moonlight's settings."
    return 0
  fi
  if [[ ! -f $conf ]]; then
    mkdir -p "$(dirname "$conf")"
    printf '[General]\naudiocfg=%s\n' "$value" > "$conf"
    return 0
  fi
  awk -v v="$value" '
    /^\[/ {
      if (sect == "General" && !done) { print "audiocfg=" v; done = 1 }
      sect = substr($0, 2, length($0) - 2)
    }
    sect == "General" && /^audiocfg=/ { if (!done) { print "audiocfg=" v; done = 1 } next }
    { print }
    END { if (!done) { if (sect != "General") print "[General]"; print "audiocfg=" v } }
  ' "$conf" > "${conf}.tmp"
  mv "${conf}.tmp" "$conf"
}

cmd_speakers() {
  local mode=${1:-} port
  case "$mode" in
    stereo|5.1|7.1) ;;
    *) die "Choose stereo, 5.1 or 7.1." ;;
  esac
  (( EUID != 0 )) || die "Run 'speakers' as the Pi's user, not with sudo."
  load_self
  port=$(kv_get "${USER_HOME}/.local/share/moonlight-pi-setup/state" hdmi_port)
  [[ $port == 1 ]] || port=0
  asoundrc_content "$mode" "$port" > "${USER_HOME}/.asoundrc.tmp"
  mv "${USER_HOME}/.asoundrc.tmp" "${USER_HOME}/.asoundrc"
  set_moonlight_audio "$mode"
  say "Speakers set to ${mode}"
}

# ---------------------------------------------------------------------------
# quit-on-shutdown
# ---------------------------------------------------------------------------
# Removing: the helper goes first, because stopping the service runs it, which
# would quit a game that's being played right now.
quit_on_shutdown_off() {
  if [[ -f $QUIT_HELPER ]] && grep -q "moonlight-pi-setup" "$QUIT_HELPER"; then
    rm -f "$QUIT_HELPER"
  fi
  if [[ -f $QUIT_SERVICE ]]; then
    systemctl disable --now "$QUIT_SERVICE_NAME" > /dev/null 2>&1 || true
    rm -f "$QUIT_SERVICE"
    systemctl daemon-reload
    systemctl reset-failed "$QUIT_SERVICE_NAME" > /dev/null 2>&1 || true
  fi
  say "The game on your PC will be left running when the Pi shuts down"
}

quit_on_shutdown_on() {
  cat > "$QUIT_HELPER" <<'EOF'
#!/usr/bin/env bash
# Installed by moonlight-pi-setup.
# Asks every paired Moonlight host to quit its running app. Hosts with nothing
# running are unaffected. Run automatically when the Pi shuts down.
CONF="$HOME/.config/Moonlight Game Streaming Project/Moonlight.conf"
[ -f "$CONF" ] || exit 0
export QT_QPA_PLATFORM=offscreen
# Moonlight lists every PC it has seen on the network, but only paired PCs
# have a saved server certificate (srvcert). Unpaired PCs can't be asked to quit.
paired_hosts() {
  awk '
    /^[0-9]+\\hostname=/ { n=$0; sub(/\\.*/, "", n); v=$0; sub(/^[^=]*=/, "", v); host[n]=v }
    /^[0-9]+\\srvcert=/  { n=$0; sub(/\\.*/, "", n); v=$0; sub(/^[^=]*=/, "", v); cert[n]=v }
    END { for (n in host) if (host[n] != "" && cert[n] != "" && cert[n] != "@ByteArray()") print host[n] }
  ' "$CONF" | sort -u
}
quit_all() {
  paired_hosts | while read -r host; do
    echo "Quitting any running app on: $host"
    timeout 10 moonlight-qt quit "$host" > /dev/null 2>&1 \
      && echo "  done" || echo "  (no response from $host)"
  done
}
# Raspberry Pi OS keeps the system journal in memory only, so it's gone after a
# reboot. Also keep a short log on disk so the last shutdown can be checked.
LOG="$HOME/.local/share/moonlight-pi-setup/quit-on-shutdown.log"
mkdir -p "$(dirname "$LOG")"
{
  echo "--- $(date '+%Y-%m-%d %H:%M:%S') ($([ -n "${INVOCATION_ID:-}" ] && echo shutdown || echo "run by hand"))"
  quit_all
} 2>&1 | tee -a "$LOG"
tail -n 200 "$LOG" > "$LOG.tmp" 2>/dev/null && mv "$LOG.tmp" "$LOG"
exit 0
EOF
  chmod 755 "$QUIT_HELPER"

  cat > "$QUIT_SERVICE" <<EOF
# Installed by moonlight-pi-setup.
[Unit]
Description=Tell Moonlight hosts to quit the running app when the Pi shuts down
Wants=network-online.target
After=network-online.target

[Service]
Type=oneshot
RemainAfterExit=yes
User=${USER_NAME}
Environment=HOME=${USER_HOME}
ExecStart=/bin/true
ExecStop=${QUIT_HELPER}
TimeoutStopSec=30

[Install]
WantedBy=multi-user.target
EOF
  systemctl daemon-reload
  systemctl enable --now "$QUIT_SERVICE_NAME" > /dev/null 2>&1
  say "The running game on your PC will be quit when the Pi shuts down"
}

# ---------------------------------------------------------------------------
# usb-handoff
# ---------------------------------------------------------------------------
# VirtualHere goes back to sharing devices all the time.
usb_handoff_off() {
  if [[ -f $HANDOFF_SERVICE ]]; then
    systemctl disable --now "$HANDOFF_SERVICE_NAME" > /dev/null 2>&1 || true
    rm -f "$HANDOFF_SERVICE"
    systemctl daemon-reload
  fi
  if [[ -f $HANDOFF_HELPER ]] && grep -q "moonlight-pi-setup" "$HANDOFF_HELPER"; then
    rm -f "$HANDOFF_HELPER"
  fi
  if [[ $(kv_get "$ROOT_STATE" vh_disabled_by_handoff) == 1 ]]; then
    systemctl enable --now "$VH_SERVICE_NAME" > /dev/null 2>&1 || true
    root_set vh_disabled_by_handoff 0
  fi
  say "USB devices are shared with your PC all the time"
}

# Share USB devices with the PC only while streaming. A watcher starts the
# VirtualHere server when a stream starts and stops it when the stream ends,
# which hands the devices back to the Pi.
usb_handoff_on() {
  virtualhere_installed || die "VirtualHere isn't installed."
  systemctl cat "$VH_SERVICE_NAME" > /dev/null 2>&1 || die "The VirtualHere service (${VH_SERVICE_NAME}) wasn't found."
  # The VirtualHere installer leaves its config writable by every user, but the
  # server runs as root.
  if [[ -f $VH_CONFIG ]]; then
    chmod 644 "$VH_CONFIG"
  fi

  cat > "$HANDOFF_HELPER" <<'EOF'
#!/usr/bin/env bash
# Installed by moonlight-pi-setup.
# Shares USB devices with the gaming PC only while Moonlight is streaming.
# Watches the Moonlight log, starts the VirtualHere server when a stream
# starts, and stops it when the stream ends, which gives the devices back to
# the Pi. A controller plugged into the Pi then works in Moonlight's menus
# between streams, and on the PC (through the VirtualHere client's Auto-Use)
# during a stream.
LOG=/tmp/moonlight.log
VH=virtualhere.service
streaming=0

start_sharing() {
  streaming=1
  echo "Stream started: sharing USB devices with the PC"
  systemctl start "$VH"
}

stop_sharing() {
  streaming=0
  echo "Stream ended ($1): giving USB devices back to the Pi"
  systemctl stop "$VH"
}

# Pick up where things are, in case this service restarted mid-stream.
last=$(grep -aE 'Starting video stream|Stopping video stream' "$LOG" 2>/dev/null | tail -n 1)
if [[ $last == *"Starting video stream"* ]] && pgrep -x moonlight-qt > /dev/null; then
  start_sharing
else
  systemctl stop "$VH"
  echo "Waiting for a stream to start"
fi

# tail -F keeps following the log when Moonlight restarts and rewrites it.
while true; do
  IFS= read -r -t 5 line
  rc=$?
  if (( rc == 0 )); then
    case $line in
      *"Starting video stream"*)
        (( streaming )) || start_sharing ;;
      *"Stopping video stream"*)
        if (( streaming )); then stop_sharing "stream closed"; fi ;;
      *"file truncated"*|*"has been replaced"*)
        if (( streaming )); then stop_sharing "Moonlight restarted"; fi ;;
    esac
  elif (( rc > 128 )); then
    # No new log lines for 5 seconds: check Moonlight hasn't closed mid-stream.
    if (( streaming )) && ! pgrep -x moonlight-qt > /dev/null; then
      stop_sharing "Moonlight closed"
    fi
  else
    exit 1   # tail stopped; systemd restarts this service
  fi
done < <(tail -n 0 -F "$LOG" 2>&1)
EOF
  chmod 755 "$HANDOFF_HELPER"

  cat > "$HANDOFF_SERVICE" <<EOF
# Installed by moonlight-pi-setup.
[Unit]
Description=Share USB devices with the gaming PC only while Moonlight is streaming
After=${VH_SERVICE_NAME}

[Service]
ExecStart=${HANDOFF_HELPER}
Restart=always
RestartSec=2

[Install]
WantedBy=multi-user.target
EOF

  # From now on the hand-off service decides when the VirtualHere server runs.
  if service_enabled "$VH_SERVICE_NAME"; then
    systemctl disable "$VH_SERVICE_NAME" > /dev/null 2>&1
    root_set vh_disabled_by_handoff 1
  fi
  systemctl daemon-reload
  systemctl enable "$HANDOFF_SERVICE_NAME" > /dev/null 2>&1
  systemctl restart "$HANDOFF_SERVICE_NAME"
  say "USB devices plugged into the Pi will move to your PC only while you're streaming"
}

# ---------------------------------------------------------------------------
# quiet-boot
# ---------------------------------------------------------------------------
# The boot options this helper added (only ever ones from QUIET_TOKENS).
added_tokens() {
  local token out=()
  for token in $(kv_get "$ROOT_STATE" quiet_tokens_added); do
    if [[ " ${QUIET_TOKENS[*]} " == *" ${token} "* ]]; then
      out+=("$token")
    fi
  done
  printf '%s' "${out[*]}"
}

quiet_boot_on() {
  [[ -f $CMDLINE_FILE && -f $CONFIG_TXT ]] || die "Can't find ${CMDLINE_FILE} or ${CONFIG_TXT}."
  backup "$CMDLINE_FILE"
  local line token added=() previous all
  line=$(head -n1 "$CMDLINE_FILE")
  for token in "${QUIET_TOKENS[@]}"; do
    if [[ " ${line} " != *" ${token} "* ]]; then
      line="${line} ${token}"
      added+=("$token")
    fi
  done
  write_cmdline "$line"
  previous=$(added_tokens)
  # shellcheck disable=SC2086  # $previous is a space-separated list on purpose
  all=$(printf '%s\n' $previous "${added[@]}" | awk 'NF && !seen[$0]++' | xargs)
  root_set quiet_tokens_added "$all"

  backup "$CONFIG_TXT"
  remove_block "$CONFIG_TXT"
  printf '%s\n[all]\ndisable_splash=1\n%s\n' "$MARK_BEGIN" "$MARK_END" >> "$CONFIG_TXT"
  say "Boot messages and the splash screen will be hidden after a restart"
}

# Removes only the boot options this helper added.
quiet_boot_off() {
  local tokens token line
  tokens=$(added_tokens)
  if [[ -n $tokens && -f $CMDLINE_FILE ]]; then
    backup "$CMDLINE_FILE"
    line=$(head -n1 "$CMDLINE_FILE")
    for token in $tokens; do
      line=$(sed -E "s/(^| )${token//./\\.}( |$)/ /g" <<<"$line")
    done
    line=$(sed -E 's/ +/ /g; s/^ //; s/ $//' <<<"$line")
    write_cmdline "$line"
    root_set quiet_tokens_added ""
  fi
  if [[ -f $CONFIG_TXT ]] && grep -qF "$MARK_BEGIN" "$CONFIG_TXT"; then
    backup "$CONFIG_TXT"
    remove_block "$CONFIG_TXT"
  fi
  say "Boot messages will show again after a restart"
}

# ---------------------------------------------------------------------------
# wifi-powersave, wifi-country
# ---------------------------------------------------------------------------
wifi_powersave_off() {
  printf '%s\n%s\n%s\n' \
    "# Added by moonlight-pi-setup: Wi-Fi power saving causes lag spikes when streaming" \
    "[connection]" \
    "wifi.powersave = 2" > "$NM_WIFI_CONF"
  systemctl reload NetworkManager 2> /dev/null || true
  # The setting above applies from the next reconnect; this applies it right away.
  local iface
  for iface in $(wifi_ifaces); do
    iw dev "$iface" set power_save off 2> /dev/null || true
  done
  say "Wi-Fi power saving is off"
}

wifi_powersave_on() {
  rm -f "$NM_WIFI_CONF"
  systemctl reload NetworkManager 2> /dev/null || true
  local iface
  for iface in $(wifi_ifaces); do
    iw dev "$iface" set power_save on 2> /dev/null || true
  done
  say "Wi-Fi power saving is on"
}

cmd_wifi_country() {
  local code=${1:-}
  [[ $code =~ ^[A-Z]{2}$ ]] || die "Use a two-letter country code, for example GB."
  grep -q "^${code}"$'\t' "$COUNTRIES" 2> /dev/null || die "Unknown country code: ${code}"
  if grep -q "cfg80211.ieee80211_regdom=${code}\b" "$CMDLINE_FILE" 2> /dev/null; then
    say "The Wi-Fi country is already ${code}"
    return 0
  fi
  command -v raspi-config > /dev/null || die "raspi-config isn't installed."
  raspi-config nonint do_wifi_country "$code" > /dev/null || die "Couldn't set the Wi-Fi country."
  say "Wi-Fi country set to ${code}"
}

# ---------------------------------------------------------------------------
# tailscale
# ---------------------------------------------------------------------------
tailscale_up() {
  local out rc line args=() arg
  out=$(mktemp)
  set +e
  # Prints a sign-in link if needed, then waits until signed in (or 10 minutes).
  tailscale up --json --timeout=600s 2>&1 | tee "$out"
  rc=${PIPESTATUS[0]}
  set -e
  if (( rc != 0 )) && grep -q "requires mentioning all non-default flags" "$out"; then
    # Tailscale was set up with extra options (for example by hand). Turn it on
    # with those same options, which tailscale lists in its message.
    line=$(grep -m1 -E '^[[:space:]]*tailscale up( |$)' "$out" || true)
    read -ra args <<<"${line#*tailscale up}"
    for arg in "${args[@]}"; do
      [[ $arg =~ ^--[a-z0-9-]+(=[^[:space:]]*)?$ ]] || { rm -f "$out"; die "Couldn't turn Tailscale on: it was set up with options this menu can't repeat."; }
    done
    rm -f "$out"
    tailscale up "${args[@]}" --json --timeout=600s
    return
  fi
  rm -f "$out"
  (( rc == 0 )) || die "Couldn't turn Tailscale on."
}

cmd_tailscale() {
  case "${1:-}" in
    install)
      if command -v tailscale > /dev/null; then
        say "Tailscale is already installed"
        return 0
      fi
      say "Downloading and installing Tailscale…"
      curl -fsSL "$TAILSCALE_INSTALL_SCRIPT" | sh || die "Tailscale couldn't be installed. Is the Pi connected to the internet?"
      root_set tailscale_installed_by_script 1
      say "Tailscale installed"
      ;;
    up)
      command -v tailscale > /dev/null || die "Tailscale isn't installed."
      tailscale_up
      ;;
    down)
      command -v tailscale > /dev/null || die "Tailscale isn't installed."
      tailscale down
      say "Tailscale is off"
      ;;
    logout)
      command -v tailscale > /dev/null || die "Tailscale isn't installed."
      tailscale logout
      say "Signed out of Tailscale"
      ;;
    *) die "Use: tailscale install|up|down|logout" ;;
  esac
}

# ---------------------------------------------------------------------------
# updates, update-setup
# ---------------------------------------------------------------------------
cmd_updates() {
  export DEBIAN_FRONTEND=noninteractive
  local list n
  case "${1:-}" in
    check)
      apt-get -o DPkg::Lock::Timeout=120 update || die "Couldn't check for updates. Is the Pi connected to the internet?"
      list=$(apt-get -s -o Debug::NoLocking=1 full-upgrade 2> /dev/null | awk '/^Inst /{print $2}')
      n=$(grep -c . <<<"$list" || true)
      say "UPDATES=${n}"
      say "PACKAGES=$(head -n 40 <<<"$list" | xargs)"
      ;;
    install)
      # Status-Fd adds "pmstatus:package:percent:description" lines, which the
      # menu shows as a progress bar.
      apt-get -y -o DPkg::Lock::Timeout=120 -o APT::Status-Fd=1 \
        -o Dpkg::Options::=--force-confdef -o Dpkg::Options::=--force-confold full-upgrade \
        || die "The updates didn't finish installing. Try again, or run 'sudo apt full-upgrade'."
      say "Updates installed"
      ;;
    *) die "Use: updates check|install" ;;
  esac
}

# Runs the latest setup script from GitHub with the current settings. It runs
# as root (it needs it throughout), and looks after the user's files itself.
cmd_update_setup() {
  load_user
  local dir="${ROOT_STATE_DIR}/update" file version
  rm -rf "$dir"
  install -d -m 700 "$dir"
  file="${dir}/moonlight-pi-setup.sh"
  say "Downloading the latest version…"
  curl -fsSL "$RAW_SCRIPT_URL" -o "$file" || die "Couldn't download the update. Is the Pi connected to the internet?"
  bash -n "$file" || die "The downloaded update looks damaged. Try again later."
  version=$(sed -n 's/^SCRIPT_VERSION="\([0-9.]*\)"$/\1/p' "$file" | head -n1)
  [[ -n $version ]] || die "The download isn't moonlight-pi-setup."
  say "Installing version ${version}…"
  cd /
  env -i PATH="$PATH" HOME="$USER_HOME" LANG=C.UTF-8 TERM=dumb MOONLIGHT_PI_USER="$USER_NAME" \
    bash "$file" --unattended
}

# ---------------------------------------------------------------------------
main() {
  local cmd=${1:-} value=${2:-}
  case "$cmd" in
    status) cmd_status ;;
    speakers) cmd_speakers "$value" ;;
    init) require_root; lock; cmd_init "$value" ;;
    quit-on-shutdown|usb-handoff|quiet-boot|wifi-powersave)
      require_root
      [[ $value == on || $value == off ]] || die "Use: ${cmd} on|off"
      lock
      load_user
      "${cmd//-/_}_${value}"
      ;;
    wifi-country) require_root; lock; cmd_wifi_country "$value" ;;
    tailscale) require_root; cmd_tailscale "$value" ;;
    updates) require_root; lock; cmd_updates "$value" ;;
    # No lock: the setup script it runs uses this helper itself.
    update-setup) require_root; cmd_update_setup ;;
    -h|--help|help) usage ;;
    *) usage >&2; exit 2 ;;
  esac
}

# Everything above is only definitions, so bash has read the whole file before
# running anything. That keeps an update replacing this file mid-run harmless.
main "$@"
